project3: project3.o activity.o
	    g++ -std=c++11 -o project3 project3.o activity.o
project3.o: project3.cpp
	    g++ -std=c++11 -o project3.o -c project3.cpp
activity.o: activity.h activity.cpp
	    g++ -std=c++11 -o activity.o -c activity.cpp
clean:
	    rm project3 project3.o activity.o
